spring:
  datasource:
    url: jdbc:mysql://localhost:3306/windowblindsiot
    username: my_user
    password: my_password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

